### ISSUE TITLE
Error with RQDA download on W10

### ISSUE THREAD

**Issue by Jhonattan38G** [Ronggui/RQDA#49]
Hi everyone.
I have had a particular error, I still cannot find the solution, and it concerns the installation of RQDA in R that has been installed in the Windows 10 OS, I have read in several forums and this problem is a bit recent (2019 - today ), several indicate some types of solutions but none have worked for me.

with:
```R
devtools :: install_github ("RQDA / RQDA", force = TRUE, INSTALL_opts = "- no-multiarch")
```
or:
```R
devtools :: install_github ("RQDA / RQDA", INSTALL_opts = "- no-multiarch")
```
is obtained:
```R
Downloading GitHub repo RQDA / RQDA @ HEAD
Error: Failed to install 'RQDA' from GitHub:
   create process 'C: /PROGRA~1/R/R-41~1.1/bin/x64/Rcmd.exe' (system error 267, Invalid directory name.
) @ win / processx.c: 1040 (processx_exec)
Warning message:
1 components of `...` were not used.

We detected these problematic arguments:
* `INSTALL_opts`

Did you misspecify an argument?
```

Do you have any information to avoid that mistake?

**Comment by BroVic** [comment]
I've written a package to help with this installation on Windows 10. Try it out [here](https://github.com/BroVic/RQDAassist)

**Comment by Jhonattan38G** [comment]
Thank you, what good developments you make
